.ddev/.gitignore
src/Form/BambooCoreSecurityTriggerFormType.php
src/Form/BambooCoreTriggerFormType.php
src/Form/BambooCoreTriggerFormWithoutPatchSetType.php
templates/bamboo_core/index.html.twig
templates/bamboo_core_security/index.html.twig

[TASK] Render build trigger buttons for 10.4

---

package.json
yarn.lock

Executed commands:
```
yarn audit
yarn add -D "@symfony/webpack-encore@^1.1.2" \
"core-js@^3.11.0" \
"webpack-notifier@^1.13.0" \
"file-loader@^6.0.0"
```

[BUGFIX] Update vulnerable npm modules

---

src/Extractor/ComposerJson.php
src/Extractor/DeploymentInformation.php
src/Service/DocumentationBuildInformationService.php
tests/Unit/Extractor/ComposerJsonTest.php
tests/Unit/Extractor/DeploymentInformationTest.php

Extend existing test to also test special handling for known packages.

[TASK] Add typo3/tailor handling for docs rendering

---

src/Service/LocalCoreGitService.php

See TYPO3-Documentation/T3DocTeam#163 for details.

[TASK] Replace `git://github.com/` with `git@github.com:`

---

.env
config/services.yaml
config/services_test.yaml
src/Controller/GithubRstIssueController.php
src/Extractor/GithubPushEventForCore.php
src/Service/GithubService.php
tests/Functional/Fixtures/GithubRstIssuePatchFetchRawFileResponse.php
tests/Functional/Fixtures/GithubRstIssuePatchRequest.php
tests/Functional/GithubRstIssueControllerTest.php

@andreasfernandez will do the rest

[FEATURE] Add end point to intercept for docs rst github issues

---

config/nginx/redirects.conf

See also: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/1886

Overhaul Extension development section of TYPO3 Explained

---

src/Extractor/DeploymentInformation.php
tests/Unit/Extractor/DeploymentInformationTest.php

[BUGFIX] Fix broken mapping for "other"

---

config/nginx/redirects.conf

related: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/2268

Move chapters on backend JavaScript into backend

---

config/nginx/redirects.conf

The extension was transfered a year ago

Redirect aoepeople/crawler to tomasnorre/crawler

---

config/nginx/redirects.conf

References https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/2480

Redirect LinkBrowser to LinkHandling

---

composer.lock

Executed command:
composer update \
"symfony/*" \
-W

[BUGFIX] Update Symfony packages

---

.github/dependabot.yml
.github/workflows/ci.yml
.github/workflows/dependabot-auto-merge.yaml

A new GitHub action is introduced that automatically merges pull requests created by dependabot. This requires changes in the repository:
- branch protection rules
- require PRs before merging
- require status checks to pass before merging
Additionally, a new check is added to the main workflow to check for a clean `git status`.

[TASK] Auto-merge dependabot PRs

---

composer.json
composer.lock

Executed command:
composer require t3g/symfony-template-bundle:^3.6.0 -W

[TASK] Update `t3g/symfony-template-bundle`

---

config/nginx/redirects.conf

before: https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/typo3/backend/latest/LanguageColumn.html
after: https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/Backend/LanguageColumn.html
before: https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/typo3/core/latest/Icon.html
after: https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/Core/Icon.html
before: https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/typo3/fluid/latest/Debug.html
after: https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/Global/Debug.html
before: https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/typo3fluid/fluid/latest/Cycle.html
after: https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/G …

[TASK] Redirects for new ViewHelperReference

---

config/nginx/redirects.conf

See https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/pull/477

Redirects: Move Installing TYPO3 chapter to TYPO3 Explained

---

config/nginx/redirects.conf

Add Redirects from TypoScript in 45 Minutes to Tsref

---

config/nginx/redirects.conf

[TASK] Redirect minor versions to LTS

---

config/nginx/redirects.conf

See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-Typoscript/pull/1484

Move HMENU special properties into data processor

---

config/nginx/redirects.conf

See https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/5242

[TASK] Establish a main "PHP architecture" chapter

---

config/nginx/redirects.conf

References https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/5530

[TASK] Move extbase domain explanations into dedicated folders

---

config/nginx/redirects.conf

References https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/pull/5575
@andreaskienast please merge

Move Dbal chapters into their own folder
