src/Service/WebHookService.php
Make sure that rendering documentation is triggered for standalone
README files as well.
Currently, supplying documentation in a dedicated Documentation
directory is supported, but also using standalone README.md or
README.rst files without the Documentation directory.
For extensions, this has the advantage that the documentation
is visible immediatedly when visiting the project on the
git hoster (e.g. GitHub) and may be a better fit for extensions
with only minimal documentation.
In any case, it is recommended to add Documentation/Settings.cfg,
so that the title is generated correctly.
Related: TYPO3-Documentation/T3DocTeam#152
=> [BUGFIX] Trigger docs rendering for standalone files

legacy_hook/tests/Unit/Fixtures/Files/Expected404.html
See TYPO3-Documentation/T3DocTeam#159 for further details.
Wait for PR https://github.com/TYPO3-Documentation/typo3-docs-typo3-org-resources/pull/4 to be merged.
=> [TASK] Replace shortcut to `typo3/surf` documentation in `Expected404.html`

legacy_hook/tests/Unit/Fixtures/Files/404.html
See TYPO3-Documentation/T3DocTeam#159 for further details.
Wait for PR TYPO3-Documentation/typo3-docs-typo3-org-resources#4 to be merged.
=> [TASK] Replace shortcut to `typo3/surf` documentation in `404.html`

.mage.yml
The core release process works in two different ways:
* Splitter
The core splitter clones the mono repository and adds each extension
repository as a new git remote to push to.
* Tagger
The tagger clones each extension repository into a distinguishable
location, creates the tags and pushes them.
All of these checkouts are now configured to be in shared/var instead
of var/ of a release and get symlinked instead after deploying a new
release as core checkouts are not related to a specific intercept
release. This also improves the performance as the checkouts don't
need to be done again.
=> [BUGFIX] Symlink core checkouts for performance reasons

config/nginx/redirects.conf
needed after Pages where moved
=> Redirects for TYPO3 explained

src/Controller/GithubRstIssueController.php, src/Service/GithubService.php, tests/Functional/Fixtures/GithubRstIssuePatchBackportRequest.php, tests/Functional/Fixtures/GithubRstIssuePatchNoDocsChangesRequest.php, tests/Functional/GithubRstIssueControllerTest.php
The hook pinged by Github when a core patch has been merged now
considers changes in the `main` branch only. Additionally, only changes
in `typo3/sysext/core/Documentation` are considered to avoid spamming
the Documentation Team's issue board with meaningless tickets.
=> [BUGFIX][DEV-1481] docs-ghiss-bridge: Limit amount of changes pushed to Github

.github/workflows/ci.yml
GitHub started to deprecate `set-output` in favor of environment
files due to security reasons. See [1] for further information.
[1] https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> [BUGFIX][DEV-1568] Migrate deprecated `set-output` to env files

.ddev/keycloak-gatekeeper.conf.tmpl, .github/workflows/ci.yml, composer.json, composer.lock, config/bundles.php, config/services.yaml, config/services_test.yaml, src/Security/LogoutSuccessHandler.php, symfony.lock, tests/Functional/Fixtures/JKU/JKUFactoryStub.php, tests/Functional/Fixtures/JKU/response.json
Due to Keycloak updates, the realm URLs need to be changed by removing the `/auth/` substring.
Executed commands:
composer require \
guzzlehttp/guzzle:^7.7.0 \
t3g/symfony-datahub-bundle:^2.0.4 \
t3g/symfony-keycloak-bundle:^2.0 \
-W
=> [TASK][INFRA-432] Update bundles and realm URL

config/nginx/redirects.conf
The 11.5 branch still has the JavaScript documentation at the old path and should not be redirected to another location.
See:
https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-CoreApi/tree/11.5/Documentation/ApiOverview/JavaScript
=> [TASK] Remove Core API / JavaScript redirect for v11.5

config/packages/framework.yaml
The configuration option `http_method_override` must be enabled in order to allow overriding the target HTTP method in forms via the `_method` field.
=> [BUGFIX][DEV-1631] Enable `http_method_override`

src/Controller/DocsRenderingController.php, src/Service/GithubService.php, tests/Functional/AdminInterface/Docs/DeploymentsControllerTest.php
When documentation gets rendered, a key `build_key` meant to be unique is generated that is used to identify a documentation registration through the whole build process. I has been discovered that the `build_key` has a low entropy, consisting of the current time and the package name whose documentation is rendered only, which is prone to collisions when multiple commits are pushed in different branches within the same repository and therefore the according webhook to Intercept is called multiple times in the same second.
When the documentation rendering succeeds, only the last documentation of said colliding `build_key` will be picked and marked as "rendered", leaving any other documentation with the same `build_key` marked as "rendering".
This issue was introduced on April 9, 2021 with …
=> [BUGFIX] Fix potential build key collision

build/phpstan-baseline.neon, composer.lock, legacy_hook/composer.lock, src/Controller/DocsRenderingController.php, src/Controller/GithubRstIssueController.php, src/Exception/GithubHookPingException.php, src/Extractor/DeploymentInformation.php, src/Utility/RepositoryUrlUtility.php, src/Validator/Constraints/InvalidCharacter.php, tests/Functional/Fixtures/DocsToBambooBadRequest.php, tests/Functional/Fixtures/DocsToBambooGithubDeletedBranchRequest.php, tests/Functional/Fixtures/DocsToBambooGithubPingRequest.php, tests/Functional/Fixtures/DocsToBambooGoodRequest.php, tests/Functional/Fixtures/DocsToBambooGoodRequestMultiBranch.php, tests/Functional/Fixtures/GithubPullRequestBadRequest.php, tests/Functional/Fixtures/GithubPullRequestGoodRequest.php, tests/Functional/Fixtures/GithubRstIssuePatchBackportRequest.php, tests/Functional/Fixtures/GithubRstIssuePatchNoDocsChangesRequest.php, tests/Functional/Fixtures/GithubRstIssuePatchRequest.php
Executed commands:
composer update -W
composer t3g:cgl:fix
composer t3g:phpstan:create-baseline
=> [TASK] Update all the things

legacy_hook/src/DocumentationVersions.php, legacy_hook/versionsJson.php
This enables the documentation Team to generate the HTML ourselves if changes are desired
Resolves https://github.com/TYPO3-Documentation/render-guides/issues/358
=> [FEATURE] Return Versions as JSON

config/nginx/redirects.conf
This commit updates the nginx redirects configuration to redirect any extension, that has not been redirected before by the dynamic configuration to extensions.typo3.org in order to get rid of `typo3cms/extensions`.
Also, the handling for `typo3cms/exceptions` has been removed, the directory is archived on the server.
Resolves: https://app.asana.com/0/1206620330068017/1207393774643690
=> [TASK] Redirect non-handled extensions to TER and remove `exceptions`

config/nginx/redirects.conf
The redirects for the old exception pages have been falsely removed and are recovered now.
=> [TASK] Recover exception redirects

legacy_hook/composer.json, legacy_hook/composer.lock, legacy_hook/linkToDocs.php, legacy_hook/src/DocumentationLinker.php, legacy_hook/src/Linker/ResponseDescriber.php
Allows to call an "API endpoint" on docs.typo3.org which can redirect to a common intersphinx identifier (like "t3coreapi:caching").
Version dependencies can also be specified.
This is possible by looking up a objects.inv.json file inside the resolved directory of the docs.typo3.org server, parse it, search for the index and then forward to the target URI.
We do not need an aggregator to merge all possible JSON files into one, because we only need to lookup the specific intersphinx repository destination.
Composer dependency 't3docs/typo3-version-handling' is utilized to provide the needed lookup maps between "intersphinx identifier" and actual rendering directory.
Example calls:
https://intercept.ddev.site/services/linkToDocs.php?shortcode=t3renderguides:available-default-inventories …
=> [FEATURE] Add linkToDocs.php helper script

legacy_hook/src/DocumentationLinker.php
Follow-up of https://github.com/TYPO3GmbH/site-intercept/pull/188
Also addresses a minor bugfix in URL replacement of "#confval-xxx" which was wrongly replaced to "#-confvalxxx"
=> [TASK] Allow linkToDocs to fallback to 'main' for unknown versions

config/nginx/redirects.conf
The documentation returns 404 if not opened on a specific branch.
=> Redirect Content Blocks to main/en-us

config/nginx/redirects.conf
As the Changelog of version main contains all other versions we only keep that one version. 
When a new tag is released the rendering of other versions is triggered (yet to be solved) and we have to delete them manually. Sometimes Google has already indexed them.
=> [BUGFIX] Redirect any non-main version of the Core Changelog to main

config/nginx/redirects.conf
The sphinx based documentation rendering has been turned off
=> Redirect from 1.0 to main in how to document

config/nginx/redirects.conf
This is used on in the Install Tool alert box
Resolves https://github.com/TYPO3-Documentation/TYPO3CMS-Tutorial-GettingStarted/issues/698
=> [BUGFIX] Redirect /Home/GettingStarted.html
